runtime: ruby32

instance_class: F2

env_variables:
  BUCKET_NAME: "skillzillabucket"

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto